// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"apiservice"
	"context"
	"flag"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
)

var _ = apiservice.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void init()")
	fmt.Fprintln(os.Stderr, "  i32 addLopHP(LopHocPhan lopHP)")
	fmt.Fprintln(os.Stderr, "  i32 addSinhVienVaoLop(string sv, string maLHP)")
	fmt.Fprintln(os.Stderr, "  i32 addSinhVienSlicesVaoLop(SinhVienSlices lsv, string maLHP)")
	fmt.Fprintln(os.Stderr, "  i32 existsLopHP(string maLHP)")
	fmt.Fprintln(os.Stderr, "  i32 existsSinhVienTrongLop(string maLHP, string maSinhVien)")
	fmt.Fprintln(os.Stderr, "  LopHocPhan getLopHocPhan(string ma)")
	fmt.Fprintln(os.Stderr, "  LopHocPhanSlices getLopHocPhanSlice()")
	fmt.Fprintln(os.Stderr, "  LopHocPhanSlices getLopHocPhanOfSinhVien(string ma)")
	fmt.Fprintln(os.Stderr, "  SinhVienSlices getSinhVienLHP(string maLHP)")
	fmt.Fprintln(os.Stderr, "  i32 delLopHP(string maLHP)")
	fmt.Fprintln(os.Stderr, "  i32 putSVOutLopHP(string maLHP, string maSV)")
	fmt.Fprintln(os.Stderr, "  i32 addSinhVien(SinhVien sv)")
	fmt.Fprintln(os.Stderr, "  i32 existsSinhVien(string maSV)")
	fmt.Fprintln(os.Stderr, "  SinhVien getSinhVien(string maSV)")
	fmt.Fprintln(os.Stderr, "  i32 delSinhVien(string maSV)")
	fmt.Fprintln(os.Stderr, "  SinhVienSlices searchSinhVien(string key)")
	fmt.Fprintln(os.Stderr, "  i32 UpdateSinhVien(SinhVien sv)")
	fmt.Fprintln(os.Stderr, "  i32 UpdateLopHP(LopHocPhan lhp)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()

	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := apiservice.NewManagerStudentClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "init":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "Init requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.Init(context.Background()))
		fmt.Print("\n")
		break
	case "addLopHP":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddLopHP requires 1 args")
			flag.Usage()
		}
		arg46 := flag.Arg(1)
		mbTrans47 := thrift.NewTMemoryBufferLen(len(arg46))
		defer mbTrans47.Close()
		_, err48 := mbTrans47.WriteString(arg46)
		if err48 != nil {
			Usage()
			return
		}
		factory49 := thrift.NewTJSONProtocolFactory()
		jsProt50 := factory49.GetProtocol(mbTrans47)
		argvalue0 := apiservice.NewLopHocPhan()
		err51 := argvalue0.Read(jsProt50)
		if err51 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AddLopHP(context.Background(), value0))
		fmt.Print("\n")
		break
	case "addSinhVienVaoLop":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "AddSinhVienVaoLop requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.AddSinhVienVaoLop(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "addSinhVienSlicesVaoLop":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "AddSinhVienSlicesVaoLop requires 2 args")
			flag.Usage()
		}
		arg54 := flag.Arg(1)
		mbTrans55 := thrift.NewTMemoryBufferLen(len(arg54))
		defer mbTrans55.Close()
		_, err56 := mbTrans55.WriteString(arg54)
		if err56 != nil {
			Usage()
			return
		}
		factory57 := thrift.NewTJSONProtocolFactory()
		jsProt58 := factory57.GetProtocol(mbTrans55)
		containerStruct0 := apiservice.NewManagerStudentAddSinhVienSlicesVaoLopArgs()
		err59 := containerStruct0.ReadField1(jsProt58)
		if err59 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.Lsv
		value0 := apiservice.SinhVienSlices(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.AddSinhVienSlicesVaoLop(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "existsLopHP":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ExistsLopHP requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ExistsLopHP(context.Background(), value0))
		fmt.Print("\n")
		break
	case "existsSinhVienTrongLop":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "ExistsSinhVienTrongLop requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ExistsSinhVienTrongLop(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getLopHocPhan":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetLopHocPhan requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetLopHocPhan(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getLopHocPhanSlice":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetLopHocPhanSlice requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetLopHocPhanSlice(context.Background()))
		fmt.Print("\n")
		break
	case "getLopHocPhanOfSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetLopHocPhanOfSinhVien requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetLopHocPhanOfSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getSinhVienLHP":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSinhVienLHP requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetSinhVienLHP(context.Background(), value0))
		fmt.Print("\n")
		break
	case "delLopHP":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DelLopHP requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DelLopHP(context.Background(), value0))
		fmt.Print("\n")
		break
	case "putSVOutLopHP":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "PutSVOutLopHP requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.PutSVOutLopHP(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "addSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "AddSinhVien requires 1 args")
			flag.Usage()
		}
		arg70 := flag.Arg(1)
		mbTrans71 := thrift.NewTMemoryBufferLen(len(arg70))
		defer mbTrans71.Close()
		_, err72 := mbTrans71.WriteString(arg70)
		if err72 != nil {
			Usage()
			return
		}
		factory73 := thrift.NewTJSONProtocolFactory()
		jsProt74 := factory73.GetProtocol(mbTrans71)
		argvalue0 := apiservice.NewSinhVien()
		err75 := argvalue0.Read(jsProt74)
		if err75 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AddSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "existsSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ExistsSinhVien requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ExistsSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSinhVien requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "delSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DelSinhVien requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DelSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "searchSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SearchSinhVien requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.SearchSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "UpdateSinhVien":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateSinhVien requires 1 args")
			flag.Usage()
		}
		arg80 := flag.Arg(1)
		mbTrans81 := thrift.NewTMemoryBufferLen(len(arg80))
		defer mbTrans81.Close()
		_, err82 := mbTrans81.WriteString(arg80)
		if err82 != nil {
			Usage()
			return
		}
		factory83 := thrift.NewTJSONProtocolFactory()
		jsProt84 := factory83.GetProtocol(mbTrans81)
		argvalue0 := apiservice.NewSinhVien()
		err85 := argvalue0.Read(jsProt84)
		if err85 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateSinhVien(context.Background(), value0))
		fmt.Print("\n")
		break
	case "UpdateLopHP":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateLopHP requires 1 args")
			flag.Usage()
		}
		arg86 := flag.Arg(1)
		mbTrans87 := thrift.NewTMemoryBufferLen(len(arg86))
		defer mbTrans87.Close()
		_, err88 := mbTrans87.WriteString(arg86)
		if err88 != nil {
			Usage()
			return
		}
		factory89 := thrift.NewTJSONProtocolFactory()
		jsProt90 := factory89.GetProtocol(mbTrans87)
		argvalue0 := apiservice.NewLopHocPhan()
		err91 := argvalue0.Read(jsProt90)
		if err91 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateLopHP(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
